global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mcp-gateway'
    static_configs:
      - targets: ['mcp-gateway:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mcp-servers'
    static_configs:
      - targets: ['mcp-server-1:3001', 'mcp-server-2:3002', 'file-tools:4001', 'web-tools:4002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
